### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by rtimmons** [mongodb/genny#296]
This is a "dummy" issue created for the purposes of attaching images and things without having to check binary things into the genny repo.

**Comment by rtimmons** [comment]
Assets from [DESIGN-4094](https://jira.mongodb.org/browse/DESIGN-4094)
![Genie_Leafie_Gradient](https://user-images.githubusercontent.com/119094/67700511-75458380-f984-11e9-9d07-4d020e9af008.jpg)

![Genie_Leafie_Flat](https://user-images.githubusercontent.com/119094/67700512-75458380-f984-11e9-9b81-668ea220b9fa.jpg)

[Genie_Leafie_Pack.zip](https://github.com/mongodb/genny/files/3779841/Genie_Leafie_Pack.zip)

**Comment by jimoleary** [comment]
Images from PERF-2177 PR
- [cmake](https://github.com/mongodb/genny/blob/1ba1419793949f9a3e59a79a114c141f7347d100/images/cmake.png)
- [debug](https://github.com/mongodb/genny/blob/1ba1419793949f9a3e59a79a114c141f7347d100/images/debug.png)
- [poplar](https://github.com/mongodb/genny/blob/1ba1419793949f9a3e59a79a114c141f7347d100/images/poplar.png)
- [toolchains](https://github.com/mongodb/genny/blob/1ba1419793949f9a3e59a79a114c141f7347d100/images/toolchains.png)

**Comment by jimoleary** [comment]
![cmake](https://user-images.githubusercontent.com/22506/112030931-ac48a600-8b32-11eb-9a09-0f3fd9138c8e.png)
![debug](https://user-images.githubusercontent.com/22506/112030946-b23e8700-8b32-11eb-9c40-a455355969bd.png)
![poplar](https://user-images.githubusercontent.com/22506/112030958-b66aa480-8b32-11eb-9857-593adb3e9832.png)
![toolchains](https://user-images.githubusercontent.com/22506/112030965-b9659500-8b32-11eb-9fa4-523640f4c95a.png)
